sudo: false
language: c
compiler:
    - gcc
install:
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            gcc-4.8
script:
    - mkdir build
    - cd build
    - cmake .. && make
