# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shayne/Code/learn-c/shake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shayne/Code/learn-c/shake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shayne/Code/learn-c/shake/CMakeFiles /home/shayne/Code/learn-c/shake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shayne/Code/learn-c/shake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shake

# Build rule for target.
shake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shake
.PHONY : shake

# fast build rule for target.
shake/fast:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/build
.PHONY : shake/fast

#=============================================================================
# Target rules for targets named vendor

# Build rule for target.
vendor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vendor
.PHONY : vendor

# fast build rule for target.
vendor/fast:
	$(MAKE) -f CMakeFiles/vendor.dir/build.make CMakeFiles/vendor.dir/build
.PHONY : vendor/fast

src/args.o: src/args.c.o

.PHONY : src/args.o

# target to build an object file
src/args.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/args.c.o
.PHONY : src/args.c.o

src/args.i: src/args.c.i

.PHONY : src/args.i

# target to preprocess a source file
src/args.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/args.c.i
.PHONY : src/args.c.i

src/args.s: src/args.c.s

.PHONY : src/args.s

# target to generate assembly for a file
src/args.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/args.c.s
.PHONY : src/args.c.s

src/keyvaluevec.o: src/keyvaluevec.c.o

.PHONY : src/keyvaluevec.o

# target to build an object file
src/keyvaluevec.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/keyvaluevec.c.o
.PHONY : src/keyvaluevec.c.o

src/keyvaluevec.i: src/keyvaluevec.c.i

.PHONY : src/keyvaluevec.i

# target to preprocess a source file
src/keyvaluevec.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/keyvaluevec.c.i
.PHONY : src/keyvaluevec.c.i

src/keyvaluevec.s: src/keyvaluevec.c.s

.PHONY : src/keyvaluevec.s

# target to generate assembly for a file
src/keyvaluevec.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/keyvaluevec.c.s
.PHONY : src/keyvaluevec.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/main.c.s
.PHONY : src/main.c.s

src/runner.o: src/runner.c.o

.PHONY : src/runner.o

# target to build an object file
src/runner.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/runner.c.o
.PHONY : src/runner.c.o

src/runner.i: src/runner.c.i

.PHONY : src/runner.i

# target to preprocess a source file
src/runner.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/runner.c.i
.PHONY : src/runner.c.i

src/runner.s: src/runner.c.s

.PHONY : src/runner.s

# target to generate assembly for a file
src/runner.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/runner.c.s
.PHONY : src/runner.c.s

src/script.o: src/script.c.o

.PHONY : src/script.o

# target to build an object file
src/script.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/script.c.o
.PHONY : src/script.c.o

src/script.i: src/script.c.i

.PHONY : src/script.i

# target to preprocess a source file
src/script.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/script.c.i
.PHONY : src/script.c.i

src/script.s: src/script.c.s

.PHONY : src/script.s

# target to generate assembly for a file
src/script.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/script.c.s
.PHONY : src/script.c.s

src/scripts.o: src/scripts.c.o

.PHONY : src/scripts.o

# target to build an object file
src/scripts.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/scripts.c.o
.PHONY : src/scripts.c.o

src/scripts.i: src/scripts.c.i

.PHONY : src/scripts.i

# target to preprocess a source file
src/scripts.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/scripts.c.i
.PHONY : src/scripts.c.i

src/scripts.s: src/scripts.c.s

.PHONY : src/scripts.s

# target to generate assembly for a file
src/scripts.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/scripts.c.s
.PHONY : src/scripts.c.s

src/shakefile/functions.o: src/shakefile/functions.c.o

.PHONY : src/shakefile/functions.o

# target to build an object file
src/shakefile/functions.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/functions.c.o
.PHONY : src/shakefile/functions.c.o

src/shakefile/functions.i: src/shakefile/functions.c.i

.PHONY : src/shakefile/functions.i

# target to preprocess a source file
src/shakefile/functions.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/functions.c.i
.PHONY : src/shakefile/functions.c.i

src/shakefile/functions.s: src/shakefile/functions.c.s

.PHONY : src/shakefile/functions.s

# target to generate assembly for a file
src/shakefile/functions.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/functions.c.s
.PHONY : src/shakefile/functions.c.s

src/shakefile/project.o: src/shakefile/project.c.o

.PHONY : src/shakefile/project.o

# target to build an object file
src/shakefile/project.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/project.c.o
.PHONY : src/shakefile/project.c.o

src/shakefile/project.i: src/shakefile/project.c.i

.PHONY : src/shakefile/project.i

# target to preprocess a source file
src/shakefile/project.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/project.c.i
.PHONY : src/shakefile/project.c.i

src/shakefile/project.s: src/shakefile/project.c.s

.PHONY : src/shakefile/project.s

# target to generate assembly for a file
src/shakefile/project.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/project.c.s
.PHONY : src/shakefile/project.c.s

src/shakefile/shakefile.o: src/shakefile/shakefile.c.o

.PHONY : src/shakefile/shakefile.o

# target to build an object file
src/shakefile/shakefile.c.o:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/shakefile.c.o
.PHONY : src/shakefile/shakefile.c.o

src/shakefile/shakefile.i: src/shakefile/shakefile.c.i

.PHONY : src/shakefile/shakefile.i

# target to preprocess a source file
src/shakefile/shakefile.c.i:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/shakefile.c.i
.PHONY : src/shakefile/shakefile.c.i

src/shakefile/shakefile.s: src/shakefile/shakefile.c.s

.PHONY : src/shakefile/shakefile.s

# target to generate assembly for a file
src/shakefile/shakefile.c.s:
	$(MAKE) -f CMakeFiles/shake.dir/build.make CMakeFiles/shake.dir/src/shakefile/shakefile.c.s
.PHONY : src/shakefile/shakefile.c.s

vendor/bstrlib.o: vendor/bstrlib.c.o

.PHONY : vendor/bstrlib.o

# target to build an object file
vendor/bstrlib.c.o:
	$(MAKE) -f CMakeFiles/vendor.dir/build.make CMakeFiles/vendor.dir/vendor/bstrlib.c.o
.PHONY : vendor/bstrlib.c.o

vendor/bstrlib.i: vendor/bstrlib.c.i

.PHONY : vendor/bstrlib.i

# target to preprocess a source file
vendor/bstrlib.c.i:
	$(MAKE) -f CMakeFiles/vendor.dir/build.make CMakeFiles/vendor.dir/vendor/bstrlib.c.i
.PHONY : vendor/bstrlib.c.i

vendor/bstrlib.s: vendor/bstrlib.c.s

.PHONY : vendor/bstrlib.s

# target to generate assembly for a file
vendor/bstrlib.c.s:
	$(MAKE) -f CMakeFiles/vendor.dir/build.make CMakeFiles/vendor.dir/vendor/bstrlib.c.s
.PHONY : vendor/bstrlib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... shake"
	@echo "... vendor"
	@echo "... src/args.o"
	@echo "... src/args.i"
	@echo "... src/args.s"
	@echo "... src/keyvaluevec.o"
	@echo "... src/keyvaluevec.i"
	@echo "... src/keyvaluevec.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/runner.o"
	@echo "... src/runner.i"
	@echo "... src/runner.s"
	@echo "... src/script.o"
	@echo "... src/script.i"
	@echo "... src/script.s"
	@echo "... src/scripts.o"
	@echo "... src/scripts.i"
	@echo "... src/scripts.s"
	@echo "... src/shakefile/functions.o"
	@echo "... src/shakefile/functions.i"
	@echo "... src/shakefile/functions.s"
	@echo "... src/shakefile/project.o"
	@echo "... src/shakefile/project.i"
	@echo "... src/shakefile/project.s"
	@echo "... src/shakefile/shakefile.o"
	@echo "... src/shakefile/shakefile.i"
	@echo "... src/shakefile/shakefile.s"
	@echo "... vendor/bstrlib.o"
	@echo "... vendor/bstrlib.i"
	@echo "... vendor/bstrlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

