#!/bin/bash

function cmd-foo()
{
    echo "cmd-foo: calling ./shake test"
    echo "-->arg0: $0"
    echo "-->arg1: $1"
    echo "-->arg2: $2"
    echo "-->arg3: $3"
    ./shake test arg1 arg2 arg3
}

function cmd-bar()
{
    echo "cmd-bar: calling ./shake test"
    echo "-->arg0: $0"
    echo "-->arg1: $1"
    echo "-->arg2: $2"
    echo "-->arg3: $3"
}
