#!/bin/bash

COMMAND_PREFIX="run-"

function run-foo()
{
    : run-foo description is this 4/0
    echo "cmd-foo: calling ./shake test"
    echo "-->arg0: $0"
    echo "-->arg1: $1"
    echo "-->arg2: $2"
    echo "-->arg3: $3"
    ./bin/Debug/shake test arg1 arg2 arg3
}

function run-bar()
{
    : i am run bar here me roar
    echo "cmd-bar: calling ./shake test"
    echo "-->arg0: $0"
    echo "-->arg1: $1"
    echo "-->arg2: $2"
    echo "-->arg3: $3"
}
